### ISSUE TITLE
Edit : Tutorial for Localization symlink is misleading

### ISSUE THREAD

**Issue by velnirsworkshop** [ImmortalRDI/Tutorial-SymLink-Convert-HotTest#1]
hey the command for symlinking .loca files is misleading instead of 

`mklink "YourGameDirectory\Data\Public\Localization\English\Modname.loca" "YourModLocalizationFolder\Modename.loca"`

it should be

`mklink "YourGameDirectory\Data\Localization\English\Modname.loca" "YourModName\Localization\English\Modename.loca"`

it gave me a bit of trouble and maybe more people will have less trouble :D

**Comment by ImmortalRDI** [comment]
Thanks for catching that oversight. Fixed.
